Basic components
SomeoneWithBFG/expertRating pull request #8
Opened 2021-07-08 15:52 UTC by SomeoneWithBFG

2021-07-09 14:04 UTC, slavasgod requested changes

2021-07-09 14:04 UTC, slavasgod commented on react-webapp/src/components/complex/Menu/index.tsx
> +    </div>
See comment above

2021-07-09 14:04 UTC, slavasgod commented on react-webapp/src/routes/index.tsx
> +
1. Add empty line
2. Why do you use `withRouter` here?

2021-07-09 14:04 UTC, slavasgod commented on react-webapp/src/styles/colors/colors.scss
> +$gray: #666666;
Empty line

2021-07-09 14:04 UTC, slavasgod commented on react-webapp/src/styles/fonts/fonts.scss
> +$basic: 'Nunito', 'sans-serif';
Empty line

2021-07-09 14:04 UTC, slavasgod commented on react-webapp/src/useCases/services/HistoryService.ts
> +}
Not sure that we need this, but ok

2021-07-09 14:04 UTC, slavasgod commented on react-webapp/src/pages/Arcticles/Articles.tsx
> +      />
When you test something like this, remove it before push

2021-07-09 14:31 UTC, SomeoneWithBFG commented on react-webapp/src/components/common/MenuUserItem/index.tsx
> +    }
text overflow

2021-07-13 13:03 UTC, slavasgod requested changes

2021-07-13 13:03 UTC, slavasgod commented on react-webapp/src/components/common/MenuUserItem/index.tsx
> +    return (
Use object spread to props

2021-07-13 13:03 UTC, slavasgod commented on react-webapp/src/components/complex/Menu/pages.ts
> +]
Empty line

2021-07-13 13:03 UTC, slavasgod commented on react-webapp/src/routes/index.tsx
> +
empty line

2021-07-14 14:18 UTC, slavasgod approved these changes

2021-07-15 07:41 UTC, merged